# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-6afc344e-c768-45fd-9af7-20921e2a782a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6afc344e-c768-45fd-9af7-20921e2a782a".device = "/dev/disk/by-uuid/6afc344e-c768-45fd-9af7-20921e2a782a";
  boot.initrd.luks.devices."luks-6afc344e-c768-45fd-9af7-20921e2a782a".crypttabExtraOpts = [ "tries=10" ];

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6149-58DA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [
      {
          device = "/var/lib/swapfile";
          size = 32 * 1024;
      }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
